### ISSUE TITLE
Should we remove the bzip2 filter?

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#124]
It kind of sucks. No better compression than zlib, but a lot slower. So why are we even providing it?

![image](https://user-images.githubusercontent.com/38856240/102394419-f734a980-3f96-11eb-9f2c-4e6a111fb3eb.png)

![image](https://user-images.githubusercontent.com/38856240/102394511-13d0e180-3f97-11eb-9543-0574fbd12ba8.png)

**Comment by edwardhartnett** [comment]
Well perhaps the graph answers my question: bzip2 does perform better with bitgroom, yielding the smallest file of all...

**Comment by czender** [comment]
Exactly. For archival purposes CR not throughput is the most important thing. I think we should retain any working compressor (Bzip2 not LZ4 (yet)) for completeness and to illustrate differences among lossless compression algorithms. CCR can be a great educational tool.

**Comment by czender** [comment]
May I suggest that you capitalize NSD in slides/text? It is an acronym for Number of Significant Digits.

**Comment by edwardhartnett** [comment]
While I agree that we should leave bzip2, because it gives the smallest size.

But I don't think that we should include any filter that does not demonstrate benefit to the user community.

Installing a filter is an invitation for someone to start using it, and then it will create a bunch of data which requires that filter. So we should not introduce filters into the ecosystem heedlessly.
