### ISSUE TITLE
What happens if I try to use the bitgroom filter with an int or char?

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#134]
I know that bit grooming is meaningless except for floats. What happens if we turn on bitgroom for an int? Does it return an error? 

Whatever is supposed to happen, we need a test for each netCDF type to make sure we get expected behavior.

Looking at the code, it seems like the type of data are not checked. Should we check the data type in nc_def_var_bitgroom, and return error for non-float/double? That would seem the most intuitive way to handle this...

Whatever we do also needs to be documented in src/ssc.c so the user knows what to expect.

**Comment by czender** [comment]
I can answer the question more quickly than write the tests. My perspective on the UI is that ease-of-use is paramount. Hence we must support the case where BG is invoked on all variables. One of the things the pre-filter callback does is check the type of the variable. Non-floating point variables are not processed by BG, and have no _Filter attributes after the operation.

**Comment by edwardhartnett** [comment]
I will document this...
