### ISSUE TITLE
Further improve bitgroom filter?

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#139]
Charlie sez:

> And a student of mine is currently testing whether we
> can shave another two bits off for the same NSD with BG
> (it's a one-line change to add before 1.1.0 is released).

**Comment by czender** [comment]
Student @jtolento has verified we can shave off two more bits. I will push this change today or tomorrow, along with the new filter ID.

**Comment by czender** [comment]
That was a bit premature. We cannot shave more bits without making exceptions to the current formula. This can be done in a future release, at least for NSD=1. For CCR 1.1 BG will be exactly as in the paper.
