### ISSUE TITLE
Should bitgroom filter leave indication it has been applied (an attribute)?

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#140]
Charlie asks:

> It seems to me that lossy filters that change the data
> should perhaps leave some such indication in the file that
> they have been applied, even after the "reverse" filter
> "uncompresses" (but not unquantizes, which is impossible) it.

I would say that it's OK if we don't do this in CCR. Here's why...

When the user writes a file with the bitgroom filter, that info is in the file. That is, the var knows the bitgroom filter has been applied, and knows the NSD. So that's good.

If they later copy that file, with NCO or in some other way, and they don't use the bitgroom filter on the copy (and why would they), then it's on them to document and understand what they are doing. 

We are producing properly documented files, with all metadata intact. We can't guarantee that this will be maintained in subsequent processing. We never can. That's up to the user.

(That said, NOAA adds an attribute for their bit-shaving, so the idea is not unreasonable. Is there an answer in the CF conventions? If not, perhaps we should propose one?)

**Comment by edwardhartnett** [comment]
Well we need to come up with a definitive answer to this question if we are going to add anything to the 1.1.0 release...

**Comment by czender** [comment]
It's fine with me if we do not add an attribute to quantized variables in CCR 1.1. For the reasons you mention.
