### ISSUE TITLE
add BitRound, DigitRound, Granular Bitgroom filters

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#141]
As discussed in email...

**Comment by czender** [comment]
Partially addressed by #196

**Comment by czender** [comment]
FYI I have working code for DigitRound and for BitRound (as applied to BitGroom). GranularBG incorporates the main features of all three, and then some, so I'm marking this issue as closed. If someone wants to separately implement these DigitRound, copy the code from the NCO baa=3 algorithm, and for BitRound copy the code from the NCO baa=5 algorithm, both in source file nco_ppc.c. GranularBG is baa=4, BTW. Adding these separately would still be helpful to isolate the individual effects of the DigitRound and BitRound algorithms. It's just not a priority and might confuse users to have so many related choices, when GBG gives the best compression which is what most users want.
