### ISSUE TITLE
BitGroom filter fails in test

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#148]
Why does the bitgroom filter fail in the test in #129?

I guess we better try to figure this out before the release... :-(

**Comment by czender** [comment]
I think it must fail because line #233 checks the BitGroomed (quantized) data for equality with the original data. We need to replace the equality check with an approximately-equal check similar to that used in tst_bitgroom.c (which should itself be improved someday). So I think this is a false-positive result. Fix the comparison and it will pass. I do not have the right setup to test multi-filter/netcdf master on my laptop (still dealing with link issues), but I am confident this explains the failure.

**Comment by czender** [comment]
Acutally the failure indicated by the logging output in #129 cannot be explained by the equality check issue I describe above. So now I think there may be more than one issue with this test. Let me look more carefully at the test...

**Comment by czender** [comment]
So it's now more clear what is happening. The test data are all integers so nothing will be Bitgroomed. What a strange test. None of the variables will be BG'd so no BG filter information will be created. Is there some kind  of assumption built into the multifilter stack that it expects a variable to have the filter info even if the filter was not employed? This could be a serious flaw, or at least "feature" that I was unaware of...

**Comment by edwardhartnett** [comment]
OK, well it is a dumb test because I just whacked it into an existing test, without even noticing that I was using int.

But that's  the value of dumb tests, they find the dumb bugs we otherwise would have missed. ;-)

How about we just check the type of the variable in nc_def_var_bitgroom? 

I have been wondering whether it would be better to return error on anything other than float. Otherwise, users are going to make the same mistake I made and never notice that bitgroom is not necessary or helpful for integer vars.

**Comment by czender** [comment]
Yes, we should write more dumb tests! I am still unsure what caused `nc4hdf.c` to bail. However I suspect it could be the filter gymnastics that the BitGroom filter uses to avoid being called for integers. I like your suggestion to modify `nc_def_var_bitgroom` to check the variable type and only call `nc_def_var_filter` for floating point types. Should `nc_def_var_bitgroom` return success or failure when called for integers?

**Comment by edwardhartnett** [comment]
I think it should fail with NC_EINVAL if you try and apply bitgroom to any non-float type.

**Comment by czender** [comment]
OK, I will implement this shortly

**Comment by edwardhartnett** [comment]
OK, this all works and is being tested.
