### ISSUE TITLE
All inq_var functions need to handle multifilters better

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#151]
I have just modified nc_inq_var_zstandard() to correctly handle the cases of multifilter vs. not. (See #149 )

This needs to be done for all the nc_inq_var_* functions in CCR.

**Comment by edwardhartnett** [comment]
This is now complete, I believe.

**Comment by czender** [comment]
All `nc_inq_var_*()` functions had a bug in multi-filter mode that was just found and fixed via #164.
