### ISSUE TITLE
make check failure in bitgroom

### ISSUE THREAD

**Issue by mathomp4** [ccr/ccr#165]
All,

I decided to try out CCR in hopes I could eventually do `ncks --ccr=Zstd -L 1 file.nc4 compressed.nc4` (which I'm not even sure NCO can do?!) and test it out. But, first I had to build everything. I think I managed to get zstd to build on my laptop, and even CCR. I had to learn about `--with-hdf5-plugin-path` but eventually I got:
```
❯ lt ../x86_64-apple-darwin19.6.0/gfortran/Darwin/lib/hdf5_plugins
.rwxr-xr-x mathomp4 staff  49 KB Mon Jan  4 10:52:32 2021  libh5bz2.0.dylib*
lrwxr-xr-x mathomp4 staff  16 B  Mon Jan  4 10:52:32 2021  libh5bz2.dylib@ ⇒ libh5bz2.0.dylib
.rwxr-xr-x mathomp4 staff 1.3 KB Mon Jan  4 10:52:32 2021  libh5bz2.la*
.rw-r--r-- mathomp4 staff 7.4 MB Mon Jan  4 10:52:32 2021  libh5bz2.a
.rwxr-xr-x mathomp4 staff 4.2 MB Mon Jan  4 10:52:35 2021  libh5bgr.0.dylib*
lrwxr-xr-x mathomp4 staff  16 B  Mon Jan  4 10:52:35 2021  libh5bgr.dylib@ ⇒ libh5bgr.0.dylib
.rwxr-xr-x mathomp4 staff 1.3 KB Mon Jan  4 10:52:35 2021  libh5bgr.la*
.rw-r--r-- mathomp4 staff 7.4 MB Mon Jan  4 10:52:35 2021  libh5bgr.a
.rwxr-xr-x mathomp4 staff  49 KB Mon Jan  4 10:52:38 2021  libh5zstd.0.dylib*
lrwxr-xr-x mathomp4 staff  17 B  Mon Jan  4 10:52:38 2021  libh5zstd.dylib@ ⇒ libh5zstd.0.dylib
.rwxr-xr-x mathomp4 staff 1.3 KB Mon Jan  4 10:52:38 2021  libh5zstd.la*
.rw-r--r-- mathomp4 staff 7.4 MB Mon Jan  4 10:52:38 2021  libh5zstd.a
```
So I must be close. However, running `make check` throws:
```
...
============================================================================
Testsuite summary for H5BZ2 1.0
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
...
```
so that's nice. I didn't even build bzip2, so I guess it found it on my laptop. Then it went on to:
```
...
============================================================================
Testsuite summary for H5BGR 1.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See example/test-suite.log
Please report to nco-bugs@lists.sourceforge.net
============================================================================
```
I figured I shouldn't report to @czender at nco-bugs, but to here. 

The log file is very...HDF5-y and I'm not good at HDF5. 
```
=======================================
   H5BGR 1.0: example/test-suite.log
=======================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: run_tests.sh
==================

HDF5-DIAG: Error detected in HDF5 (1.10.7) thread 0:
  #000: H5S.c line 1246 in H5Sis_simple(): not a dataspace
    major: Object atom
    minor: Unable to find atom information (already closed?)
WARNING: Cannot apply filter "BitGroom filter (Zender, 2016 GMD: http://www.geosci-model-dev.net/9/3199/2016)" filter because data space is not simple.
HDF5-DIAG: Error detected in HDF5 (1.10.7) thread 0:
  #000: H5D.c line 152 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: H5Dint.c line 338 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #002: H5L.c line 1605 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: H5L.c line 1846 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #004: H5Gtraverse.c line 848 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: H5Gtraverse.c line 624 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: H5L.c line 1652 in H5L__link_cb(): unable to create object
    major: Links
    minor: Unable to initialize object
  #007: H5Oint.c line 2496 in H5O_obj_create(): unable to open object
    major: Object header
    minor: Can't open object
  #008: H5Doh.c line 300 in H5O__dset_create(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #009: H5Dint.c line 1235 in H5D__create(): I/O filters can't operate on this dataset
    major: Invalid arguments to routine
    minor: Unable to initialize object
  #010: H5Z.c line 906 in H5Z_can_apply(): unable to apply filter
    major: Data filters
    minor: Error from filter 'can apply' callback
  #011: H5Z.c line 866 in H5Z__prepare_prelude_callback_dcpl(): unable to apply filter
    major: Data filters
    minor: Error from filter 'can apply' callback
  #012: H5Z.c line 771 in H5Z__prelude_callback(): filter parameters not appropriate
    major: Data filters
    minor: Error from filter 'can apply' callback
BitGroom filter is available for quantization and decoding.
....Create dataset ................
failed to create dataset.
FAIL run_tests.sh (exit status: 1)
```
I configured with:
```
$ ./configure \
--prefix=/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin \
--includedir=/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/include/ccr \
--with-hdf5-plugin-path=/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/lib/hdf5_plugins \
--enable-fortran --enable-bitgroom --enable-zstd --enable-parallel-tests --disable-docs \
CC=mpicc FC=mpifort CXX=mpic++ F77=mpifort
```
Any ideas? It is *HIGHLY* probably I screwed up the build somewhere before ccr, but I thought I'd ask if this is a familiar bug.

**Comment by czender** [comment]
Matt,

Thanks for this report. Once this is sorted out, you should be able to use the CCR from `ncap2`, e.g.,

**Comment by mathomp4** [comment]
> Matt,
> 
> Thanks for this report. Once this is sorted out, you should be able to use the CCR from the latest (4.9.8-alphaXX) snapshot of `ncap2`, e.g.,
> 
> ```
> ncap2 -O -7 --ccr=Zstd -L 3 --cnk_map=nc4 -s '*quark=one' ~/nco/data/in.nc ~/foo.nc
> ncap2 -O -7 --ccr=BitGroom -L 3 --cnk_map=nc4 -s '*quark=one' ~/nco/data/in.nc ~/foo.nc
> ```

Oh..hmm. So I could use `ncap2` as a "compressor" by essentially multiplying everything by 1.0 into a new file? Hmm.

**Comment by edwardhartnett** [comment]
Could it be a scalar?

It says in the documentation here:
https://portal.hdfgroup.org/display/HDF5/H5S_IS_SIMPLE

H5S_IS_SIMPLE determines whether a dataspace is a simple dataspace.
[Currently, all dataspace objects are simple dataspaces; complex dataspace
support will be added in the future.]

**Comment by czender** [comment]
I doubt that a scalar is a non-simple dataspace because I have tested HDF5 and the BitGroom filter on every size and shape of number possible. My guess is that Matt is triggering something that has not been seen before because he is using a new compiler combination (`CC=mpicc FC=mpifort CXX=mpic++ F77=mpifort`) or a newer HDF5 version. Just a guess. @mathomp4 please post the results of `ccr-config --all`.

**Comment by czender** [comment]
> Oh..hmm. So I could use ncap2 as a "compressor" by essentially multiplying everything by 1.0 into a new file? Hmm.

@mathomp4 You don't need to multiply by  anything. But ncap2 must be given a "do nothing" script like I showed otherwise it will complain and exit.

**Comment by mathomp4** [comment]
> I doubt that a scalar is a non-simple dataspace because I have tested HDF5 and the BitGroom filter on every size and shape of number possible. My guess is that Matt is triggering something that has not been seen before because he is using a new compiler combination (`CC=mpicc FC=mpifort CXX=mpic++ F77=mpifort`) or a newer HDF5 version. Just a guess. @mathomp4 please post the results of `ccr-config --all`.

@czender Here you go. Took me a while as `ccr-config` isn't installed into `$prefix/bin` and I was going nuts "It's in my PATH!". But if I run from the `src` tree:
```console
❯ ./ccr-config --all

This ccr 1.1.0 has been built with the following features:

  --cc            -> mpicc
  --cflags        -> -I/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/include/ccr   -I/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/include/    -I/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/include/zlib    -I/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/include/szlib    -I/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/include/jpeg    -I/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/include/hdf5    -I/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/include/hdf    -I/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/include/netcdf    -I/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/include/udunits2    -I/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/include/gsl    -I/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/include/antlr2   -I/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/include/netcdf -I/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/include
  --libs          -> -L/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/lib -lccr

  --has-fortran   -> yes
  --fc            -> mpifort
  --fflags        -> -I/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/include/ccr -g -O2
  --flibs         -> -L/Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/lib -lccrf -lccr
  --has-f90       -> no
  --has-f03       -> no

  --has-bitgroom  -> yes
  --has-bzip2     -> yes
  --has-lz4       -> no
  --has-zstd      -> yes
  --has-par       -> yes
  --has-multifilters      -> no

  --prefix        -> /Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin
  --includedir    -> /Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/include/ccr
  --libdir        -> /Users/mathomp4/Baselibs/ESMA-Baselibs-main-with-ccr-zstd/x86_64-apple-darwin19.6.0/gfortran/Darwin/lib
  --version       -> ccr 1.1.0
``` 

I am a bit surprised by this:
```
  --has-f90       -> no
  --has-f03       -> no
```

As for other info, I'm using (for this test):
```console
❯ mpicc --version
gcc (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

❯ mpifort --version
GNU Fortran (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

❯ mpirun --version
mpirun (Open MPI) 4.1.0

Report bugs to http://www.open-mpi.org/community/help/
```
Pretty boring GCC and Open MPI. On macOS, though, so all the fun of case-insensitive filesystem.

**Comment by mathomp4** [comment]
> > Oh..hmm. So I could use ncap2 as a "compressor" by essentially multiplying everything by 1.0 into a new file? Hmm.
> 
> @mathomp4 You don't need to multiply by anything. But ncap2 must be given a "do nothing" script like I showed otherwise it will complain and exit.

Oh... I thought you were showing an example of using `ncap2` on a file with a variable `quark`!

**Comment by czender** [comment]
One little-known` ncap2` feature  is that it will make a variable (here `quark`) RAM-based  (not disk-based) if you precede it with an asterisk. It behaves like a normal variable, yet incurs no read/write time and does not change the input or output files. So it truly is a 'do-nothing loop'. 
You have also identified `ccr-config` issues that I can duplicate (`f03` and `f90` presence), thanks, that is now #170.
Regarding this bug report, I currently (and baselessly) suspect that `has-par` may lead to this issue. @edwardhartnett have you tested `make check` with MPI/has-par enabled yet? I have not. It's unclear what else could cause a dataset to report itself as "not simple". It must be something fundamental like MPI, is my thinking.

**Comment by edwardhartnett** [comment]
Yes I have tested make check with par IO builds. I think theres a workflow that does that too...

**Comment by mathomp4** [comment]
> I have tested netcdf-c-4.8.0 and it works fine with the current release of netcdf-fortran. There are no API changes in 4.8.0, so fortran works the same with it.

Ah. Now I remember, I can't use the latest netcdf-fortran release because of [my nf-config issue](https://github.com/Unidata/netcdf-fortran/issues/270). But, I can either stick with v4.5.2 or use `main`.

**Comment by mathomp4** [comment]
@edwardhartnett Well, after figuring out how to get around a zstd CMake bug on macOS, I'm getting close. First thing, my `configure` line is still:
```
          ./configure --prefix=$(prefix) \
                      --includedir=$(prefix)/include/ccr \
                      --with-hdf5-plugin-path=$(prefix)/lib/hdf5_plugins \
                      --enable-fortran \
                      --enable-bitgroom \
                      --enable-zstd \
                      --enable-parallel-tests \
                      --disable-docs \
                      CC=$(NC_CC) FC=$(NC_FC) CXX=$(NC_CXX) F77=$(NC_F77) 
```
but with that I get:
```
configure: error: Only shared library builds allowed.
```
and, if I run `./configure --help` I do see the default is yes:
```
  --enable-shared[=PKGS]  build shared libraries [default=yes]
  --enable-static[=PKGS]  build static libraries [default=yes]
```
So I added `--disable-static` but:
```
checking whether to build shared libraries... no
checking whether to build static libraries... yes
...
configure: error: Only shared library builds allowed.
```
Okay,  let's try `--disable-static --enable-shared`:
```
checking whether to build shared libraries... yes
checking whether to build static libraries... no
...
configure: error: Only shared library builds allowed.
```
Huh. Well, it says it's building shared, but then...doesn't? Any ideas what I might be getting wrong?

**Comment by edwardhartnett** [comment]
Well @mathomp4 what crazy thing are you doing?

This problem is coming from these lines in configure.ac:

```
if test "x$enable_shared" = xno; then
   AC_MSG_ERROR([Only shared library builds allowed.])
fi

```

The enable_shared variable is set (if I understand correctly) by LT_INIT, and should be "yes" unless you use the --disable-shared flag.

This is because I can't figure out how to handle static builds, though Elena from HDF5 just looks at me funny and tells me of course it will work. However, she often looks at me funny, so we can't go by that.

So why is enable_shared not "yes" for you?

Can you try a clean clone of the current master branch? And use only: --with-hdf5-plugin-path --enable-fortran --enable-parallel-tests.

If that doesn't work, post the complete output of configure and attach a copy of the config.log file. I'm going to do a release shortly, so if we can get this resolved, any necessary fix can go into the next release...

**Comment by edwardhartnett** [comment]
I cannot get CCR to work without shared builds. If you are trying static only builds - that's the problem.

**Comment by edwardhartnett** [comment]
OK, can we try with the latest versions of everything? There is netcdf-c-4.8.1, hdf5-1.12.1, and I'm releasing ccr-1.3.0. ;-)
