### ISSUE TITLE
autoupdate for configure.ac

### ISSUE THREAD

**Issue by czender** [ccr/ccr#178]
Running `autoupdate` would eliminate many/most `autoreconf` warnings on my systems. However, @edwardhartnett is better suited to this since he is the autotools king and would be better able to track down any problems that result.

**Comment by edwardhartnett** [comment]
I'll give it a try...

**Comment by edwardhartnett** [comment]
Autoupdate does nothing for us:

> autoupdate: 'configure.ac' is unchanged

We are already up to date.

**Comment by czender** [comment]
Indeed. My mistake. Thanks for checking into this.
