### ISSUE TITLE
Try better sample data for tst_gfs_data_1.c

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#180]
> Hi Ed,
> 
> First, thanks again for all you CCR efforts.
> I see v1.2 is out and truly robust. Hoooray!
> 
> Regarding compression ratio, a factor of 10 is unrealistic
> for climate/weather data. Whereas random numbers can barely
> be compressed at all (except for their exponents), continuous
> geophysical fields generally span only a few orders of magnitude
> and contain many essentially random bits at the "end", i.e.,
> bits 20-31, and can only be compressed by about 10-40% (ocean
> data can do better because of all the missing values).
> In any case, the highest lossless compression ratio expected is
> less than 2.
> 
> Which begs your question, why does your algorithm below produce
> a field with such high CRs? One reason may be that most of
> the data are in the same decade or three, and all numbers are
> positive, so the exponent/sign bits are easy to encode.
> Second reason: the denominator (surprisingly, to me) produces
> predictable bit patterns that in base 10 look like this:
> 
> 1000/1001
> .99900099900099900099
> 1002/1001
> 1.00099900099900099900
> 1003/1001
> 1.00199800199800199800
> 2000/1001
> 1.99800199800199800199
> 2001/1001
> 1.99900099900099900099
> 2003/1001
> 2.00099900099900099900
> 
> Try making the denominator a function of cnt and my_rank,
> e.g.,
> 
> value_data[cnt] = my_rank * 1000 + cnt / sqrt(my_rank+cnt+1);
> 
> Curious to see what that does...
>

**Comment by edwardhartnett** [comment]
@czender I changed the data as you suggested. Not much difference in file sizes:

```
unlim, comp, level, shuffle, meta wr time (s), data wr rate (MB/s), file size (MB)
0, none, 0, 0, 0.17944, 610.58, 7266.68
0, zlib, 1, 0, 0.959941, 356.266, 685.467
0, zlib, 4, 0, 0.493637, 223.81, 506.38
0, zlib, 9, 0, 0.473725, 55.5689, 506.56
0, szip, 0, 0, 0.503548, 401.841, 443.976
0, zstd, 1, 0, 0.226282, 1254.88, 523.7
0, zstd, 10, 0, 0.278445, 198.807, 523.118
0, zstd, 20, 0, 0.445773, 10.6624, 452.108
```

**Comment by czender** [comment]
Hmm. I'm stumped. We may need an applied math person to suggest a number generating algorithm that yields compression ratios (of about 1.4-1.8) that are closer to real-world climate data.

**Comment by edwardhartnett** [comment]
or use some real data...

But for now, we will call this good enough. ;-)
