### ISSUE TITLE
We need a logo...

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#183]
We need a logo! I have one in mind...

**Comment by edwardhartnett** [comment]
![ccr-logo](https://user-images.githubusercontent.com/38856240/122649095-7becb580-d0e9-11eb-8898-4ebc12d9150b.png)

**Comment by czender** [comment]
That's a smashing logo!

![image](https://user-images.githubusercontent.com/5597049/122653955-23271800-d0fd-11eb-95a4-ce1fca2bf30e.png)

**Comment by edwardhartnett** [comment]
We have a very nice logo from Jennifer Oxelson, the designer of the netCDF logo (which I see everywhere now...)

Thanks Jen!
