### ISSUE TITLE
Treat netCDF default _FillValues the same as explicitly defined _FillValues in BitGroom filter

### ISSUE THREAD

**Issue by czender** [ccr/ccr#185]
If my new understanding is correct, the BG filter should treat netCDF default _FillValues the same as explicitly defined _FillValues. This means the `!has_mss_val` blocks should check for default _FillValues, and the `has_mss_val` blocks should check for both explicitly-defined and default _FillValues.

**Comment by czender** [comment]
Close #185 via #186

**Comment by edwardhartnett** [comment]
But this should only happen when there is not already an explicitly defined fill value, right?

That is, the default fill values are only fill values if the user did not define a fill value. If the user does define a fill value, then the default values may be used as actual data, and will not be considered fill values.

Is that the way you coded it?

**Comment by czender** [comment]
Your explanation makes sense. I did not understand the purpose of the defaults that way, so I'll drop the double comparison when there is an explicitly defined fill value in the next patch.

**Comment by czender** [comment]
#187 Reverted the "double and" so it's now OK to BG the default values if and only if a _FillValue has been explicitly defined
