### ISSUE TITLE
netcdf-c quantize comes up with different answer than bitgroom filter for these type conversion, but I think it's OK.

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#194]
@czender I need some help here.

As you know, I am implementing quantize in netcdf-c. I have been using the bitgroom filter as a reference for the netcdf-c code. In CCR I have test/tst_bitgroom.c, and in netcdf-c nc_test4/tst_quantize.c, which run the same tests, and come up with the same answers.

However, I have hit a case where the answers are different. But I think it's OK.

Here's the code that causes the trouble. I create a file with two vars, a float and a double, and turn on quantization (nsd=3) for both of them. Then I each element separately, with the nc_put_var1_xxx() function, using different starting types. What should happen is the data get converted to float/double, then quantization is applied.

```
	unsigned char uc = 99;
	signed char sc = -99;
	unsigned short us = 9999;
	signed short ss = -9999;
	unsigned int ui = 9999999;
	signed int si = -9999999;
	unsigned long long int ull = 999999999;
	signed long long int sll = -999999999;

        /* Create file. */
        if (nc_create(FILE_NAME, NC_NETCDF4, &ncid)) ERR;

        /* Create dims. */
        if (nc_def_dim(ncid, X_NAME, DIM_LEN_8, &dimid)) ERR;

        /* Create the variables. */
        if (nc_def_var(ncid, VAR_NAME, NC_FLOAT, NDIM1, &dimid, &varid1)) ERR;
        if (nc_def_var(ncid, VAR_NAME_2, NC_DOUBLE, NDIM1, &dimid, &varid2)) ERR;

        /* Set up quantization. */
        if (nc_def_var_quantize(ncid, varid1, NC_QUANTIZE_BITGROOM, NSD_3)) ERR;
        if (nc_def_var_quantize(ncid, varid2, NC_QUANTIZE_BITGROOM, NSD_3)) ERR;

        /* Write data. */
	index = 0;
        if (nc_put_var1_uchar(ncid, varid1, &index, &uc)) ERR;
        if (nc_put_var1_uchar(ncid, varid2, &index, &uc)) ERR;
	index = 1;
        if (nc_put_var1_schar(ncid, varid1, &index, &sc)) ERR;
        if (nc_put_var1_schar(ncid, varid2, &index, &sc)) ERR;
	index = 2;
        if (nc_put_var1_ushort(ncid, varid1, &index, &us)) ERR;
        if (nc_put_var1_ushort(ncid, varid2, &index, &us)) ERR;
	index = 3;
        if (nc_put_var1_short(ncid, varid1, &index, &ss)) ERR;
        if (nc_put_var1_short(ncid, varid2, &index, &ss)) ERR;
	index = 4;
        if (nc_put_var1_uint(ncid, varid1, &index, &ui)) ERR;
        if (nc_put_var1_uint(ncid, varid2, &index, &ui)) ERR;
	index = 5;
        if (nc_put_var1_int(ncid, varid1, &index, &si)) ERR;
        if (nc_put_var1_int(ncid, varid2, &index, &si)) ERR;
	index = 6;
        if (nc_put_var1_ulonglong(ncid, varid1, &index, &ull)) ERR;
        if (nc_put_var1_ulonglong(ncid, varid2, &index, &ull)) ERR;
	index = 7;
        if (nc_put_var1_longlong(ncid, varid1, &index, &sll)) ERR;
        if (nc_put_var1_longlong(ncid, varid2, &index, &sll)) ERR;

```

Here is some output from the netcdf-c code showing the output:

```
*** Checking BitGroom values with type conversion between ints and floats...
0 float_data_in : 99.00000000   : 0x42c60000 expected 99.00000000   : 0x42c60000
1 float_data_in : -99.00000000   : 0xc2c60000 expected -99.00000000   : 0xc2c60000
2 float_data_in : 9996.00000000   : 0x461c3000 expected 9996.00000000   : 0x461c3000
3 float_data_in : -9996.00000000   : 0xc61c3000 expected -9996.00000000   : 0xc61c3000
4 float_data_in : 9998336.00000000   : 0x4b189000 expected 9998336.00000000   : 0x4b189000
5 float_data_in : -9998336.00000000   : 0xcb189000 expected -9998336.00000000   : 0xcb189000
6 float_data_in : 999817216.00000000   : 0x4e6e6000 expected 999817216.00000000   : 0x4e6e6000
7 float_data_in : -999817216.00000000   : 0xce6e6000 expected -999817216.00000000   : 0xce6e6000

```

The second number is the hex that is the floating point stored in the file. All these end with 000, as I expect. (Since I am writing each value individually, all get zeros, and none get ones). And when I look at the output, I see the number indeed has 3 significant digits preserved, but no more.

So this looks right.

But the bitgroom filter program gives different results:

```
*** Checking BitGroom values with type conversion between ints and floats...
0 float_data_in : 99.00000000   : 0x42c60000 expected 99.00000000   : 0x42c60000
1 float_data_in : -99.03124237   : 0xc2c60fff expected -99.03124237   : 0xc2c60fff
2 float_data_in : 9996.00000000   : 0x461c3000 expected 9996.00000000   : 0x461c3000
3 float_data_in : -9999.99902344   : 0xc61c3fff expected -9999.99902344   : 0xc61c3fff
4 float_data_in : 9998336.00000000   : 0x4b189000 expected 9998336.00000000   : 0x4b189000
5 float_data_in : -10002431.00000000   : 0xcb189fff expected -10002431.00000000   : 0xcb189fff
6 float_data_in : 999817216.00000000   : 0x4e6e6000 expected 999817216.00000000   : 0x4e6e6000
7 float_data_in : -1000079296.00000000   : 0xce6e6fff expected -1000079296.00000000   : 0xce6e6fff

```

In this case, we see that the endings alternate between 0s and 1s as we expect from the bitgroom filter.

The difference is that, in the filter case, HDF5 applies the filter after the fact to all values, whereas in the netcdf-c case, the values have quantization applied one by one, as the user writes them.

**Comment by czender** [comment]
> The difference is that, in the filter case, HDF5 applies the filter after the fact to all values, whereas in the netcdf-c case, the values have quantization applied one by one, as the user writes them.

Ahh. I see what is happening. I had to think many many minutes to understand. The BG filter in netCDF always uses the "even" index loop in the algorithm, because it receives one value at a time, whereas the CCR/HDF5 filter uses both even and odd loops because it applies the filter at the end. I prefer the CCR/HDF5 behavior because it does what BG is intended to do, i.e., alternate quantization between successive array elements, regardless of in which order the elements are written. 

I have only a vague understanding of why netCDF behaves differently. Something about copying the user data to an internal array (so the user can free the data without corrupting what netCDF will write) before the data are written to disk. Is there a (simple) way to get netCDF to "hold-off" on applying BG until immediately before the data are flushed to disk?

**Comment by edwardhartnett** [comment]
No there is no simple way to get netCDF to hold off. As soon as it can, netCDF calls H5Dwrite() with the data, and hands it over to HDF5. In the case of this code, there are 5 calls to H5Dwrite(), one for each value. 

In netcdf-c quantize is applied before H5Dwrite, with filters, it is applied after H5Dwrite.

It's OK, no user will ever do what I have done in this test, and even if they do, they will simply be getting non-bitgroomed quantization, which will still work. We can't protect against every bad access pattern...

**Comment by edwardhartnett** [comment]
I wanted to keep a record of this, so I created the issue, but it is not a bug, so there is nothing to be done, and I will close the issue...
