### ISSUE TITLE
what is the future for BitGroom in CCR, now that it's in netcdf-c?

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#197]
We are getting bitgroom in netcdf-c now, which is great. It's not yet released, but will be in the next release.

What should happen to the bitgroom filter in CCR?

I submit that we don't actually want anyone to use CCR bitgroom. This would produce files that are unreadable to anyone without the bitgroom filter, whereas using netcdf-c creates bitgroomed files that are fully backward compatible.

So I suggest that we move all development of additional bitgroom features to netcdf-c, and remove the bitgroom filter from CCR.

@czender , what say you? What's your idea how the bitgroom filter is going to evolve in CCR?

**Comment by edwardhartnett** [comment]
Let me address each point:
* Having bitgroom in netcdf-c has still permits using it with many different compression filters in CCR. That is, CCR can provide a new filter, and users can turn on bitgrooming in netCDF and use the new filter for compression.
* There surely cannot be many existing workflows with the bitgroom filter. It is not at all widespread.
* We need to make the netCDF code more weildy for you.

Does NCO use CCR?

How can we make the netcdf-c version of the code more hospitable to you? What would it take to make that your "home" version of the bitgroom code?

**Comment by czender** [comment]
Good. I am working on a netCDF-c patch for Granular BG. Hope to finish it by next week.
