### ISSUE TITLE
release version 1.3.0

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#199]
With the removal of the need for shared only builds, and the new bitgroom algorithm, I suggest we do a release. @czender any objections?

**Comment by czender** [comment]
Yes, I agree these advances warrant a new version. Thanks in advance for preparing a release!

**Comment by edwardhartnett** [comment]
@czender are we ready for release?

**Comment by czender** [comment]
No known bugs and a few solid new features and an upcoming conference all point to "Yes".
