### ISSUE TITLE
Add suggested Acknowledgement text to homepage

### ISSUE THREAD

**Issue by czender** [ccr/ccr#215]
I'm writing the Year 2 annual progress report for this proposal, and to comply with the proposal commitments we need to add a suggested acknowledgement text. My draft text is: 

> The Community Codec Repository (CCR) used in this work is supported by the National Science Foundation under Grant No. OAC-2004993.

Feedback welcome, @edwardhartnett

**Comment by edwardhartnett** [comment]
No problem as far as I'm concerned. Put it in the README.md at the bottom.
