### ISSUE TITLE
BitGroom filter does not install depcomp from clean build, requires automake --add_missing

### ISSUE THREAD

**Issue by czender** [ccr/ccr#26]
At least for me on MacOS. Workaround is `cd ccr/hdf5_plugins/BITGROOM;automake --add_missing`. Probably an autotools subtlety we will solve eventually.

**Comment by edwardhartnett** [comment]
Is this still happening?

When I check out a clean build I can do autoreconf -i at the top level, and every needed file seems to be generated. Also it's working in the CI builds...

**Comment by czender** [comment]
Yes, unfortunately,  it occurs on at least two machines I have tried, though not all machines. Thankfully not on the Travis server. No idea what's  happening. My autoconf version is 2.69, which seems old, though.

**Comment by edwardhartnett** [comment]
I will add macos testing in the next release. See #81

**Comment by edwardhartnett** [comment]
The build is now running on a macos GitHub build, but that doesn't mean we have resolved every mac issue. ;-)

autoconf 2.69 is what I am using, so that is not the problem. What is your automake version? Mine is 1.16.1.

**Comment by czender** [comment]
This problem has occurred on at least two machines (sastrugi and one I cannot remember) for me.
Sastrugi has autoconf 2.69 and automake 1.16.3.

**Comment by edwardhartnett** [comment]
Well shoot.

**Comment by czender** [comment]
This problem occurs for me on glace.ess.uci.edu, a Ubuntu 16.04 LTS machine. After `autoreconf` and `configure`, building dies because `depcomp` must be manually installed in the BZIP2 filter directory. Problem and workaround are the same in all other respects as those described above.

**Comment by edwardhartnett** [comment]
Do you do autoreconf -i? The -i is important...

**Comment by czender** [comment]
I have been using `autoreconf -i -f`. Perhaps I should drop the `-f`? It looks like it may undo some of what `-i` does.

**Comment by edwardhartnett** [comment]
Yes, try it without the -f. This is working on the macos GitHub build.

**Comment by edwardhartnett** [comment]
Can we close this? The MacOS CI build is working well...

**Comment by czender** [comment]
Yes, closing this since it has not troubled me for awhile. Will re-open if it re-surfaces.
