### ISSUE TITLE
Why don't tests in ~/ccr/test pass?

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#30]
Why don't tests in ~/ccr/test pass?

**Comment by edwardhartnett** [comment]
OK, the problem here is that Dennis changed the way that the inq functions work for filters and now the old code doesn't work.

We could adapt to the version of netCDF, but instead I recommend that we just demand the latest version and only deal with that.

Moving forward, Dennis will not be changing this again, so we don't always have to be at the latest format, it just means that starting with CCR-1.1, netcdf-c-4.7.4 or better will be required.

**Comment by edwardhartnett** [comment]
OK, I think I've got it figured out. We should not be trying to H5Zregister any of the filters. Instead, we must let HDF5 find them at startup.

For this to happen, we must do make install before we do make check.

If I build like this:

`autoreconf -i && CFLAGS='-g -Wall' HDF5_PLUGIN_DIR=/home/ed/hdf5_plugin1 CPPFLAGS='-I/usr/local/hdf5-1.10.6/include -I/usr/local/netcdf-c-4.7.4_hdf5-1.10.6/include' LDFLAGS='-L/usr/local/hdf5-1.10.6/lib -L/usr/local/netcdf-c-4.7.4_hdf5-1.10.6/lib' ./configure --disable-zstd --disable-bitgroom --enable-docs --with-hdf5-plugin-dir=/home/ed/plug1 --prefix=/home/ed/local/ccr && make -j clean && make -j`

And do a make all install, then my plugins are built and installed, and the plugins are in /home/ed/plug1.

Then, my test can succeed like this, if I comment out all the H5Zregister code in ccr.c:

```
 HDF5_PLUGIN_PATH=/home/ed/plug1 ./tst_bzip2 

*** Checking HDF5 variable functions some more.
*** Checking HDF5 variable compession and filters...ok.
*** Tests successful!
```

My idea had been to test them before installing, and that is usual, but the plugin directory business makes that hard. At least for the 1.1 release, we will require make install before make check.

**Comment by czender** [comment]
Nice detective work!

**Comment by edwardhartnett** [comment]
What this also means is that the function ccr_initialize() is not needed.
