### ISSUE TITLE
Should we add nf_def/inq_var_flt() C code for every filter?

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#31]
2a. Should we add nf_def/inq_var_flt() C code for every filter?
2b. Should we add nf_def/inq_var_flt() Fortran code for every filter?

**Comment by edwardhartnett** [comment]
Yes, I believe we should.

It is possible for the user to use filters without these convenience functions, but it's a challenge to figure out and get work. These convenience functions are much simpler to use and also easy to write.

**Comment by czender** [comment]
I agree that the C/Fortran bindings are helpful. It's a clean way for model developers to get their preferred filters from end-to-end, and it helps the CCR grow roots in the community. I mainly wanted to make sure that the bzip2/lz4 bindings were not "one-off" trials. I will write BitGroom and Zstandard bindings soon, and we can close this issue then. In the future, I'll make this a regular practice now that you've fixed the binding tests.
