### ISSUE TITLE
How to implement chained filters (e.g., lossy->lossless)

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#33]
How to implement chained filters (e.g., lossy->lossless)

**Comment by edwardhartnett** [comment]
It may be that this cannot be easily done, or done at all, before the next release of netcdf-c. There is a big set of filter changes in the next release including better support for multiple filters.

**Comment by czender** [comment]
Agreed. This is not doable the right way in CCR 1.1. Wait for netCDF 4.8.0.

**Comment by edwardhartnett** [comment]
However, after the 4.8.0 netcdf-c release, this will be achieved by calling the def filter commands in the order you want the filter applied...

**Comment by edwardhartnett** [comment]
I think we will have to try this, using the develop branch of netcdf-c. It's what everyone is going to be most interested in...
