### ISSUE TITLE
tst_bitgroom and tst_zstandard fail on Travis bionic, work elsewhere

### ISSUE THREAD

**Issue by czender** [ccr/ccr#51]
Why?  Commented out in Makefile.am to get clean build. May need to extensively annotate with printf or echo the log-file contents to to debug.

**Comment by edwardhartnett** [comment]
I am having a similar sounding issue with LZ4 and suspect it has to do with whether the filter is installed in the right place or is being found in the right place.

**Comment by czender** [comment]
That makes sense. Maybe redefine the HDF5_PLUGIN_PATH.

**Comment by czender** [comment]
Fixed by #65 #67 and earlier build environment changes by @edwardhartnett
