### ISSUE TITLE
ChangLog? RELEASE_NOTES.md? Or just GitHug release notes?

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#52]
I see you are updating a ChangeLog. In the presence of the excellent features of GitHub for tracking issues and pull requests, I think this effort can be redirected. Or else if you can convince me of the value I will start editing it as well with my changes.

It is very necessary to have some way of communicating the major and important changes of each release. On the netCDF projects, Ward uses a RELEASE_NOTES.md file (https://github.com/Unidata/netcdf-c/blob/master/RELEASE_NOTES.md). From this I have adopted the useful practice of putting links to the GitHub issues so that interested users can click through and see all the details. This is one reason I always make sure there is an issue describing everything I'm doing, so that it can be properly documented for users (and me, in 6 months, when I complete forget all the details).

(And as a power user of netCDF, I have often had cause to click-through and check out the issues in detail, which is why I started adding all these links to my other projects' release notes.)

What I have been doing on my other projects for this is simply using the GitHub release notes. Normally when I do a release, I start the release notes for the next release, so there is always a set of release notes ready to update. Then, when I complete an issue that I want to make sure the users are notified of, I go to the release notes on GitHub and edit them, adding the item to the "New in This Release" section of the release notes. (And make sure to hit the "save draft" button at the bottom or your changes will be lost.)

I have put up some release notes for the 1.1.0 version of CCR. Instead of using the ChangeLog (or in addition), I suggest you add updates to the release notes.

The idea is that the release notes are just just cut and paste into an email to the netCDF mailing list and wherever else we want to announce a new release. By keeping the release notes ready to go and up to date, we make it really easy to do a release at any time.

@czender  what do you think?

**Comment by mathomp4** [comment]
Random aside from a lurker here[1], but if you do go with a ChangeLog, I recommend [changelog-enforcer](https://github.com/dangoslen/changelog-enforcer) as a possible help/hindrance. I've added it to a couple repos I manage to sort of force people to change the changelog where we have one.

[1] Lurker because I've tried a couple times to get [SZ](https://github.com/szcompressor/SZ) and [zfp](https://github.com/LLNL/zfp) to work with HDF5/netCDF and gave up in "I don't know what I'm doing". But I'm trying to learn from compression masters. 😄

**Comment by czender** [comment]
I am happy to try-out your method. Where are the release notes you mention above that I am to add to? I looked around there is nothing obvious in root or docs.

**Comment by edwardhartnett** [comment]
If you go to the main GitHub page, you will see the link to "Releases" on the right. That takes you to all the release notes, the very topmost one is labeled "Version 1.1.0".

Here's a link to it:
https://github.com/ccr/ccr/releases
