### ISSUE TITLE
what does the BITGROOM filter do to fill values?

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#70]
It should ignore them...

**Comment by czender** [comment]
agreed. it does. try it and see. the algorithm is as documented in the paper except it does not add a "number_of_significant_digits" attribute to each processed variable. That information is now in the _Filter attribute, though interpreting that is not for the faint of heart. So perhaps the filter should add the plain attribute to variables, too. Thoughts?

**Comment by edwardhartnett** [comment]
What needs to be avoided is the case where a user has a bunch of fill values, then they groom their data, and then pack it.

Then they unpack it, and now the fill values are not exactly the same, so they are not detected as fill values.

One way to avoid this would be to check what the fill value of a var is when grooming it, and don't touch those values. (That is don't groom fill values.) As I understand you, this is what is done.

In terms of the nbits, there should be an inq_ function with the bitgroom filter which returns nbits for any var for which the filter is applied. If that exists, we don't need an attribute. Adding an attribute to a var is a big step because otherwise a filter is invisible in the file to netcdf, since filters are applied transparently. Adding an attribute changes the number of attributes, which is a big change.

**Comment by czender** [comment]
Neither BitGroom nor any lossy filter in the CCR will touch values that are defined as the _FillValue. 

I agree that lossless filters should not add attributes. For filters that change numerical data because they are lossy, I think adding an attribute can be justified. An attribute is clearer to end-users than a new API function. That is why the BitGroom in NCO adds the attribute.

**Comment by czender** [comment]
My approach to this version 1.1, BTW, is to work through these discussions and prototype implementations until we are satisfied and in agreement. I have a bunch of lossy filters that can be implemented in a v2 once the architecture and features stabilize.
