### ISSUE TITLE
Release version 1.1.0

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#82]
We are getting close to release...

**Comment by edwardhartnett** [comment]
@czender I'm getting ready to do this release. Speak now to stop me, or save it for the next release...

**Comment by czender** [comment]
All systems go. Pull the trigger dude!

**Comment by edwardhartnett** [comment]
I think we better resolve #148

**Comment by edwardhartnett** [comment]
OK, now I think we are ready to release 1.1.0...
