### ISSUE TITLE
Improve documentation of zstandard

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#88]
We have:
```
/**
 * Turn on Zstandard compression for a variable.
 *
 * @param ncid File ID.
 * @param varid Variable ID.
 * @param level From -131072 to 22 (depends on Zstandard version). 
 * when compressing. (Zstandard default level is 3).
 *
 * @return 0 for success, error code otherwise.
 * @author Charlie Zender
 */

```

What is the guidance on picking the level? Does higher level number mean more compression? What is the meaning of a negative level number? How can there be a default?

@czender do you know?

**Comment by edwardhartnett** [comment]
Also in the inq function we say the level goes from 1 to 9. Let's get our story straight...

```
/**
 * Learn whether Zstandard compression is on for a variable, and, if so,
 * the level setting.
 *
 * @param ncid File ID.
 * @param varid Variable ID.
 * @param zstandardp Pointer that gets a 0 if Zstandard is not in use for this
 * var, and a 1 if it is. Ignored if NULL.
 * @param levelp Pointer that gets the level setting (from 1 to 9), if
 * bzlip2 is in use. Ignored if NULL.
 *
 * @return 0 for success, error code otherwise.
 * @author Ed Hartnett
 */

```

(Also aren't you the author of this one @czender ?)

**Comment by edwardhartnett** [comment]
When I change the value from 3 to other values, I see the exact same file size as a result:

 ```
 -rw-rw-r--  1 ed ed 4008192 Dec  1 09:01 tst_perf_uncompressed.nc
  -rw-rw-r--  1 ed ed 3587506 Dec  1 09:01 tst_perf_zstandard_12.nc
  -rw-rw-r--  1 ed ed 3587506 Dec  1 09:01 tst_perf_zstandard_15.nc
  -rw-rw-r--  1 ed ed 3587501 Dec  1 08:58 tst_perf_zstandard_3.nc
  -rw-rw-r--  1 ed ed 3587501 Dec  1 09:00 tst_perf_zstandard_4.nc
  -rw-rw-r--  1 ed ed 3587502 Dec  1 09:00 tst_perf_zstandard_5.nc
  -rw-rw-r--  1 ed ed 3587502 Dec  1 09:01 tst_perf_zstandard_6.nc
  -rw-rw-r--  1 ed ed 3587502 Dec  1 09:00 tst_perf_zstandard_7.nc
  -rw-rw-r--  1 ed ed 3587502 Dec  1 09:01 tst_perf_zstandard_9.nc
```

**Comment by czender** [comment]
LIFO: Yes, that is suspicious. I will try to look into this today. I read a lot of Zstandard code and docs and have a fair idea of. what the compression levels mean and will include better guidance. Yes, I must have copied your code and not changed the name.

**Comment by edwardhartnett** [comment]
OK, I committed test/tst_perf.c if you want to start from there. It does various levels of zstandard compression and produces the files I list above.

**Comment by czender** [comment]
The good news is the current implementation works for my "real world" tests of compressing a ~1 GB climate data file. The CR gets better and the throughput worsens as the compression level increases from 3  to 10. I have not yet examined the `tst_perf.c` code yet I am optimistic since the implementation of the Zstandard filter works in "real world" cases.
```
zender@sastrugi:~/ccr$ time nccopy -7 -F *,32015,3 ${DATA}/bm/eamv1_ne30np4l72.nc ~/eam_zstd.nc
3.19user 1.36system 0:04.69elapsed 97%CPU (0avgtext+0avgdata 2086264maxresident)k
0inputs+0outputs (0major+528862minor)pagefaults 0swaps
zender@sastrugi:~/ccr$ ls -l ~/eam_zstd.nc
-rw-r--r-- 1 zender staff 625542759 Dec  1 16:56 /Users/zender/eam_zstd.nc
zender@sastrugi:~/ccr$ time nccopy -7 -F *,32015,10 ${DATA}/bm/eamv1_ne30np4l72.nc ~/eam_zstd.nc
21.83user 1.48system 0:23.43elapsed 99%CPU (0avgtext+0avgdata 2086192maxresident)k
0inputs+0outputs (0major+532932minor)pagefaults 0swaps
zender@sastrugi:~/ccr$ ls -l ~/eam_zstd.nc
-rw-r--r-- 1 zender staff 622622220 Dec  1 16:57 /Users/zender/eam_zstd.nc

```

**Comment by edwardhartnett** [comment]
OK good to know. I will take another stab at it tomorrow...

**Comment by czender** [comment]
Answers gleaned from `zstd.h`

1. What is the guidance on picking the level? 

Zstandard currently (v. 1.4.5) supports levels from -131072 to 22.
The exact range depends on the Zstandard version. Earlier versions have smaller ranges.
The Zstandard default level is 3. This is fine for many purposes.
Pick levels 0 <= CLEVEL < 20 for reasonable compression times.

2. Does higher level number mean more compression?

> The library supports regular compression levels from 1 up to ZSTD_maxCLevel(),
> which is currently 22. Levels >= 20, labeled `--ultra`, should be used with
> caution, as they require more memory. The library also offers negative
> compression levels, which extend the range of speed vs. ratio preferences.
> The lower the level, the faster the speed (at the cost of compression).
> 

3. What is the meaning of a negative level number?

See above. Negative levels produce (much) faster speeds, and worse CR.

4. How can there be a default?

The Zstandard library default is 3. Specifying CLEVEL=0 sets the
library to the internal default level (3) which itself is set here in `zstd.h`:

```
#ifndef ZSTD_CLEVEL_DEFAULT
#  define ZSTD_CLEVEL_DEFAULT 3
#endif

```

**Comment by czender** [comment]
I used the command-line zstd compression method to emulate the filter test in tst_perf. The results indicate that the tst_perf_uncompressed.nc file may not be complex enough to allow incremental CR improvements with the compression level, i.e., the size barely changes:

```
zender@sastrugi:~/ccr/test$ ls -l *tst_perf*.nc
-rw-r--r-- 1 zender staff 4008192 Dec  4 15:28 tst_perf_uncompressed.nc
-rw-r--r-- 1 zender staff 3587497 Dec  4 15:28 tst_perf_zstandard_1.nc
-rw-r--r-- 1 zender staff 3587497 Dec  4 15:28 tst_perf_zstandard_2.nc
-rw-r--r-- 1 zender staff 3587501 Dec  4 15:28 tst_perf_zstandard_3.nc
-rw-r--r-- 1 zender staff 3587501 Dec  4 15:28 tst_perf_zstandard_4.nc
-rw-r--r-- 1 zender staff 3587502 Dec  4 15:28 tst_perf_zstandard_5.nc
-rw-r--r-- 1 zender staff 3587502 Dec  4 15:28 tst_perf_zstandard_6.nc
-rw-r--r-- 1 zender staff 3587502 Dec  4 15:28 tst_perf_zstandard_7.nc
-rw-r--r-- 1 zender staff 3587502 Dec  4 15:28 tst_perf_zstandard_8.nc
-rw-r--r-- 1 zender staff 3587502 Dec  4 15:28 tst_perf_zstandard_9.nc
zender@sastrugi:~/ccr/test$ zstd -1 tst_perf_uncompressed.nc -o ~/foo_zstd1.nc
tst_perf_uncompressed.nc : 89.31%   (4008192 => 3579827 bytes, /Users/zender/foo_zstd1.nc) 
zender@sastrugi:~/ccr/test$ zstd -2 tst_perf_uncompressed.nc -o ~/foo_zstd2.nc
tst_perf_uncompressed.nc : 89.31%   (4008192 => 3579814 bytes, /Users/zender/foo_zstd2.nc) 
zender@sastrugi:~/ccr/test$ zstd -3 tst_perf_uncompressed.nc -o ~/foo_zstd3.nc
tst_perf_uncompressed.nc : 89.31%   (4008192 => 3579796 bytes, /Users/zender/foo_zstd3.nc) 
zender@sastrugi:~/ccr/test$ zstd -4 tst_perf_uncompressed.nc -o ~/foo_zstd4.nc
tst_perf_uncompressed.nc : 89.31%   (4008192 => 3579796 bytes, /Users/zender/foo_zstd4.nc) 
zender@sastrugi:~/ccr/test$ zstd -5 tst_perf_uncompressed.nc -o ~/foo_zstd5.nc
tst_perf_uncompressed.nc : 89.31%   (4008192 => 3579782 bytes, /Users/zender/foo_zstd5.nc) 
zender@sastrugi:~/ccr/test$ zstd -9 tst_perf_uncompressed.nc -o ~/foo_zstd9.nc
tst_perf_uncompressed.nc : 89.31%   (4008192 => 3579768 bytes, /Users/zender/foo_zstd9.nc) 
zender@sastrugi:~/ccr/test$ 

```
So what initially appears suspicious probably reflects a feature, not a bug, of Zstandard. It starts out with very close to optimal compression for simple datasets. To verify this we can try a testing on a more comlex target, aka my real world ~1 GB dataset, with the CCR codec and with the zstd command line utility:
```
for cmp_lvl in 1 2 3 4 5 6 7 8 9; do
    nccopy -7 -F *,32015,$cmp_lvl ${DATA}/bm/eamv1_ne30np4l72.nc ~/eam_zstd_ccr_${cmp_lvl}.nc
    zstd -f -$cmp_lvl ${DATA}/bm/eamv1_ne30np4l72.nc -o ~/eam_zstd_cmd_${cmp_lvl}.nc
done
```
The results are:
```
zender@sastrugi:~$ ls -l eam_zstd_ccr_?.nc
-rw-r--r-- 1 zender staff 630007641 Dec  4 15:42 eam_zstd_ccr_1.nc
-rw-r--r-- 1 zender staff 627578145 Dec  4 15:42 eam_zstd_ccr_2.nc
-rw-r--r-- 1 zender staff 625542759 Dec  4 15:42 eam_zstd_ccr_3.nc
-rw-r--r-- 1 zender staff 625006839 Dec  4 15:42 eam_zstd_ccr_4.nc
-rw-r--r-- 1 zender staff 624020079 Dec  4 15:42 eam_zstd_ccr_5.nc
-rw-r--r-- 1 zender staff 623684619 Dec  4 15:42 eam_zstd_ccr_6.nc
-rw-r--r-- 1 zender staff 623266177 Dec  4 15:43 eam_zstd_ccr_7.nc
-rw-r--r-- 1 zender staff 623093594 Dec  4 15:43 eam_zstd_ccr_8.nc
-rw-r--r-- 1 zender staff 622884052 Dec  4 15:44 eam_zstd_ccr_9.nc
zender@sastrugi:~$ ls -l eam_zstd_cmd_?.nc
-r--r--r-- 1 zender staff 628263686 Apr  4  2018 eam_zstd_cmd_1.nc
-r--r--r-- 1 zender staff 625643272 Apr  4  2018 eam_zstd_cmd_2.nc
-r--r--r-- 1 zender staff 623454170 Apr  4  2018 eam_zstd_cmd_3.nc
-r--r--r-- 1 zender staff 622797061 Apr  4  2018 eam_zstd_cmd_4.nc
-r--r--r-- 1 zender staff 621611014 Apr  4  2018 eam_zstd_cmd_5.nc
-r--r--r-- 1 zender staff 621321085 Apr  4  2018 eam_zstd_cmd_6.nc
-r--r--r-- 1 zender staff 621123726 Apr  4  2018 eam_zstd_cmd_7.nc
-r--r--r-- 1 zender staff 621070776 Apr  4  2018 eam_zstd_cmd_8.nc
-r--r--r-- 1 zender staff 620882076 Apr  4  2018 eam_zstd_cmd_9.nc

```
The compression ratios for both methods improve in lockstep with the compression level. Therefore I conclude the codec is working as expected. The documentation was updated via #92. Please re-open this issue if  you disagree or have concerns.

**Comment by edwardhartnett** [comment]
Looks good! Sorry, re-opened this issue by accident.
